### PR TITLE
Add unpinned dependencies to fix #254

### LINKED ISSUE #254: Pin Unpinned Dependencies in requirements.txt
## Motivation
As I was browsing through the project, PyCharm notified me that there were dependencies that it wasn't aware of (generally this happens when they aren't pinned in requirements.txt). Some of these dependencies are pretty important, like `flask` and `alembic`, and should be pinned to prevent potential issues between environments/installs.

## Changes
- Add unpinned projects to requirements.txt
- Remove unused imports

### PR DESCRIPTION
**Pull request by aaron-suarez**
These 4 dependencies are used but were unpinned.

### CODE REVIEW

**Comment by mc962** [comment]
It looks like the following packages are still unpinned:
- werkzeug
- click

Pycharm was a bit unsure about `healthcheck`
And algoliasearch may also be outdated

**Comment by aaron-suarez** [comment]
@irvingpop I went ahead and rebased this (a few times because it was rather out of date 😅 )

Can you take a look?

**Comment by irvingpop** [comment]
Looks good, ship it!

**Comment by aaron-suarez** [comment]
I did a `pip list` on the container running locally and this is what I got.. Do you know a good way to check if any of these aren't pinned but should be? I would think all the different ones are transitive dependencies but I'm not really sure how to verify that

```sh
# pip list
Package            Version   
------------------ ----------
alembic            1.3.2     
algoliasearch      2.1.0     
attrs              19.3.0    
bandit             1.5.1     
certifi            2019.11.28
chardet            3.0.4     
Click              7.0       
coverage           5.0.3     
entrypoints        0.3       
flake8             3.7.9     
Flask              1.1.1     
Flask-Cors         3.0.8     
Flask-Limiter      1.2.1     
Flask-Migrate      2.5.2     
Flask-SQLAlchemy   2.4.1     
gitdb              4.0.2     
GitPython          3.1.0     
idna               2.9       
importlib-metadata 1.5.0     
itsdangerous       1.1.0     
Jinja2             2.11.1    
limits             1.5.1     
Mako               1.1.2     
MarkupSafe         1.1.1     
mccabe             0.6.1     
more-itertools     8.2.0     
packaging          20.3      
pbr                5.4.4     
pip                20.0.2    
pluggy             0.13.1    
prometheus-client  0.7.1     
psycopg2-binary    2.8.4     
py                 1.8.1     
py-healthcheck     1.9.0     
pycodestyle        2.5.0     
pyflakes           2.1.1     
pyparsing          2.4.6     
pytest             5.3.2     
pytest-cov         2.8.1     
pytest-mock        2.0.0     
python-dateutil    2.8.1     
python-editor      1.0.4     
PyYAML             5.3       
requests           2.23.0    
setuptools         45.2.0    
six                1.14.0    
smmap              3.0.1     
SQLAlchemy         1.3.13    
SQLAlchemy-Utils   0.36.1    
stevedore          1.32.0    
urllib3            1.25.8    
uWSGI              2.0.18    
wcwidth            0.1.8     
Werkzeug           1.0.0     
wheel              0.34.2    
zipp               3.1.0     
```

**Comment by aaron-suarez** [comment]
I did a grep for all the import statements, I didn't see anything that wasn't covered here. This will solve the immediate problem. If we later need to add something we missed, that's fine. 

@irvingpop will you merge if you're good with it? Thanks

**Comment by irvingpop** [comment]
I'm good with it, merging.

**Comment by irvingpop** [comment]
Regarding your question @aaron-suarez about the entire dep tree, this is definitely kind of problem that tools like [Poetry](https://python-poetry.org/) and [pip-compile](https://github.com/jazzband/pip-tools/) - they let you focus on a much shorter list of top-level dependencies, but will handle locking in the entire tree for maximum safety at deployment time.

Because back-end already uses Poetry, it makes the most sense for this project to migrate over to that.

**Pull request merged**
