### PR TITLE
fix(tests): decoupled hardcoded strings from tests

### LINKED ISSUE #116: Testing should be decoupled from specific response strings
Per this comment https://github.com/OperationCode/resources_api/pull/111#discussion_r266947365

Some tests basically test the exact string returned from the server rather than the fact that the exception handler is called. This can be problematic if we ever need to change those strings and the exception is still called fine (meaning the test should pass). An example of this is here:
https://github.com/OperationCode/resources_api/blob/10c20bf8d5df5ee4b387eb79da6bf75ae90d9b83/tests/unit/test_routes.py#L299

There are several instances of this throughout the tests.

### PR DESCRIPTION
**Pull request by RanadeepPolavarapu**
Resolves #116

### CODE REVIEW

**Comment by aaron-suarez** [comment]
@wimo7083 You had a much stronger opinion than I did about how these tests looked. Can you please review this one to see if it solves the problem? I don't think we had clear acceptance criteria when we originally discussed the issue.

**Comment by aaron-suarez** [comment]
@RanadeepPolavarapu I spoke with @wimo7083 on slack and we think the change is fine. If you would please fix your conflicts, I'll go ahead and get this merged

**Comment by RanadeepPolavarapu** [comment]
@aaron-suarez Awesome. Sure, I'll resolve conflicts once I'm home from work.

**Comment by RanadeepPolavarapu** [comment]
@aaron-suarez I have resolved the merge conflicts.

**Pull request merged**
