### PR TITLE
Update pyyaml requirements to 4.2b1 or newer

### PR DESCRIPTION
**Pull request by phongvdoan**
Issue #109

### CODE REVIEW

**Comment by aaron-suarez** [comment]
@phongvdoan I just got a chance to try it out and run it. When you run `make setup` now, it lets us know that our use of `yaml.load` is deprecated. The error reads as follows:

```
/src/app/cli.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)
```

Since we're updating the dependency in this PR, can we go ahead and update our use of that function before I merge it? You should be able to find correct usage in the docs for PyYAML, if you have trouble let me know and I'll point you in the right direction.

Thanks so much for your contribution!

**Comment by phongvdoan** [comment]
Ok, I will work on it today/tomorrow.

**Comment by phongvdoan** [comment]
From the docs, I got PyYAML version 5.1, you will get a warning, but the function will still work, but I can disable the warning.

**Comment by phongvdoan** [comment]
Or I can specify the Loader to be either BaseLoader, SafeLoader, or FullLoader. FullLoader seems like the default for 5.1, but if we are loading untrusted input then SafeLoader would be recommended..

Jeez I am learning a lot.

**Comment by phongvdoan** [comment]
It is done!

**Comment by aaron-suarez** [comment]
Looks great, thanks for adding that change as well. I'm also glad you learned a lot!

**Pull request merged**
