### PR TITLE
add /GET category route

### PR DESCRIPTION
**Pull request by VeraButler**
This returns an empty array to the browser.

### CODE REVIEW

**Comment by aaron-suarez** [comment]
@VeraButler Can you go ahead and fix those flake errors?

**Comment by VeraButler** [comment]
@aaron-suarez I will look into it tomorrow morning.

**Comment by aaron-suarez** [comment]
K. Remember that you can do `flake8 app` from the project root directory and it will tell you the errors you need to fix.

I appreciate the movement on this 😄

**Comment by VeraButler** [comment]
@wimo7083 No worries.  :)

**Pull request merged**
