### PR TITLE
Params for filtering resources on language or category. 

### PR DESCRIPTION
**Pull request by heavysaturn**
Opening a new pull request because the other one fell victim to the GitHub problems that have been happening today and yesterday.

This PR solves #29, allowing you to filter GET requests to the resources endpoint by language, category, or both. The requests are still paginated in the same way, with the filtering being applied _before_ the pagination is done. All filters are caps insensitive.

### CODE REVIEW

**Comment by aaron-suarez** [comment]
There's some things going on here I don't quite understand. We may need to optimize the queries at some point, and perhaps some of this will be solved by some of the data cleaning issues. But I pulled it down and tried it out and everything worked as I expected it. I like the change to the paginator, less parameters is simpler.

Thanks for this @heavysaturn

**Comment by heavysaturn** [comment]
@aaron-suarez I'd be happy to shed some light on any particulars you don't understand, or add more comments to clarify parts that need clarification, if necessary.

As for the queries, because of the way SQLA and Postgres work, these are already quite fast. SQL Alchemy will turn these kinds of queries into highly performant single raw SQL queries, something like
```python
query = Resource.query.filter(
    Resource.languages.any(
        Language.name.ilike(language)
    )
)
```

will be turned into something like this:
```sql
SELECT * 
FROM resource 
WHERE %s 
ILIKE ANY(resource.languages)
```

and then `language` will be interpolated into the `%s`. 

This is a case insensitive group membership comparison that checks if the language is in the list of languages inside the ANY. It's basically as fast as it gets. Everything is handled in a single query, and everything is handled by the database rather than the backend.

**Comment by aaron-suarez** [comment]
I am not familiar with `ILIKE`, but I know that `LIKE` is slower than `=` and it can't take advantage of indexing if I understand correctly. However, in this particular app, we're letting people search with arbitrary strings, so perhaps that's faster than string comparisons in python...

**Comment by heavysaturn** [comment]
@aaron-suarez ILIKE is just case insensitive LIKE. I did this because I noticed some of the resources had differences in case - like `python` and `Python`. This way, the filter doesn't care about case at all and finds all python resources like it should.

It's true that `LIKE` is slower than `=` and it's possible that you could shave off some microseconds by optimizing these queries, but considering how few rows are ever going to be in this database, this would fall under what Donald Knuth refers to as "premature optimization" (which he then goes on to characterize as "the root of all evil"). These queries are already so fast that optimizing them is, at best, a waste of time, and, at worst, going to hurt readability.

**Pull request merged**
