### PR TITLE
#246 - Break Apart routes Module Into Package

### PR DESCRIPTION
**Pull request by Jitsusama**
This PR, as per the request in #246, breaks apart the routes module into a new package, where separate modules organized by functional area.

### CODE REVIEW

**Comment by Jitsusama** [comment]
I just noticed there are conflicts, I guess my master branch was too old. That's a bummer.

**Comment by aaron-suarez** [comment]
Yeah, and speaking of that, this is going to cause conflicts with probably every open PR that there is. We should probably consider a rollout strategy for this. Or at least wait to merge it until all of the currently open PRs are merged (though I don't want to block you indefinitely on the batch create one, I'll rebase that if I have to). I just don't want to break everyone else's WIP stuff

**Comment by Jitsusama** [comment]
What do you recommend? Should I start from scratch off of current master, or not? For selfish reasons, I'd like to get this brought in before Hacktoberfest is over.

**Comment by aaron-suarez** [comment]
The rules of Hacktoberfest say that you need to _open_ 4 PRs, not that those PRs need to be merged. If we need to let this sit into November that's fine. I wouldn't recommend opening the PR to break up the test_routes.py just yet, but you can open two other PRs to get them in for Hacktoberfest even while this one remains unmerged.

If you need help deciding what else to open up, hit me up on slack, I have a couple ideas.

**Comment by C-Lion** [comment]
You can also just submit a PR called Issue #XXX WIP. As long as the repo manager doesn't reject it  or mark it as spam it should count as valid for Hactoberfest.

**Comment by Jitsusama** [comment]
Thanks @C-Lion; I'll just rebase when things settle down a bit.

**Comment by Jitsusama** [comment]
Retrying in #267.

**Comment by aaron-suarez** [comment]
This also closes #246

**Pull request closed without merging**
